AI_Builders/AI_Builders/urls.py
"""AI_Build URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  url
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('', include('aiapp.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AI_Builders/aiapp/urls.py
from django.urls import path
from aiapp import views


urlpatterns=[
path('',views.home),
path('index/',views.index),
path('register/',views.register),
path('login/',views.login),
path('logout/',views.logout),
path('category/',views.category,name="create_category"),
path('categorylist/',views.categorylist),
path('catdelete/',views.catdelete),
path('catedit/',views.catedit),
path('catupdate/',views.catupdate),
path('task/',views.task,name="create_task"),
path('tasklist/',views.tasklist),
path('taskdelete/',views.taskdelete),
path('taskedit/',views.taskedit),
path('taskupdate/',views.taskupdate),
# path('addcourse/',views.addcourse),
path('courselist/',views.courselist),
path('coursefind/',views.coursefind),
# path('courseupdate/',views.courseupdate),
path('coursedelete/',views.coursedelete),
path('create_course/',views.createcourse ,name="create_course"),
path('update_course/<str:pk>/',views.updatecourse ,name="update_course"),
path('create_help/',views.createhelp ,name="create_help"),
path('helplist/',views.helplist),
path('update_help/<str:pk>/',views.updatehelp ,name="update_help"),
path('helpdelete/',views.helpdelete),
path('create_boot/',views.createboot ,name="create_boot"),
path('bootlist/',views.bootlist),
path('update_boot/<str:pk>/',views.updateboot ,name="update_boot"),
path('bootdelete/',views.bootdelete),







]

AI_Builders/app/urls.py
from django.contrib import admin
from django.urls import path,include
from .Views.apiView import *
from .Views.webView import *

from django.views.generic import TemplateView
urlpatterns = [
    path('myadmin/index',index),



    path('api/signup', UserSave.as_view(), name='UserSave'),
    path('api/login', Login.as_view(), name='login'),
    path('api/send/otp', verify_otp.as_view(), name='verify_otp'),
    path('api/verify/otp/input', verify_otp_input.as_view(), name='verify_otp_input'),
    path('api/forgot/password', ForgotPassword.as_view(), name='ForgotPassword'),

    path('api/courses/list', getCoursesList.as_view(), name='getCoursesList'),
    path('api/courses/details/list', getCoursesDetailsList.as_view(), name='getCoursesDetailsList'),
    path('api/course/topics/list', getCourseTopicList.as_view(), name='getCourseTopicList'),

    path('api/category/list', getCategoryList.as_view(), name='getCategoryList'),

    path('api/task/list', getTaskList.as_view(), name='getTaskList'),

    path('api/bootcamp/list', getBootcampList.as_view(), name='getBootcampList'),

    path('api/help', HelpSave.as_view(), name='HelpSave'),

    path('api/webinar/list', getWebinarList.as_view(), name='getWebinarList'),

]

AI_Builders/aiapp/models.py
from django.db import models

# Create your models here.
class customeruser_tb(models.Model):
	name=models.CharField(max_length=100,default='')
	usertype = models.IntegerField(default=0)
	status = models.BooleanField(default=False)
	phonecode = models.CharField(max_length=100,default='')
	phoneno = models.CharField(max_length=100,default='')
	email=models.CharField(max_length=100,default='')
	password = models.CharField(max_length=100,default='')
	usercode = models.CharField(max_length=100,default='')

	def __str__(self):
		return str(self.name)

class category_tb(models.Model):
	catname=models.CharField(max_length=100,default='')
	catcode =models.CharField(max_length=100,default='')

	def __str__(self):
		return str(self.catname)

class task_tb(models.Model):
	taskname=models.CharField(max_length=100,default='')
	taskcode =models.CharField(max_length=100,default='')

	def __str__(self):
		return str(self.taskname)

class course_tb(models.Model):
	coname=models.CharField(max_length=200,default='')
	cocode =models.CharField(max_length=100,default='')
	cotype =models.CharField(max_length=100,default='')
	cstatus=models.CharField(max_length=100,default='')
	username=models.ForeignKey(customeruser_tb,on_delete=models.CASCADE,related_name="customeruser_username")
	catname=models.ForeignKey(category_tb,on_delete=models.CASCADE,related_name="category_catname")
	taskname=models.ForeignKey(task_tb,on_delete=models.CASCADE,related_name="task_taskname")

	def __str__(self):
		return str(self.coname)

	class Meta:
		db_table = "course_tb"	

class Help(models.Model):
	STATUS_Response = (
        ('Posted', 'Posted'),
        ('Responded', 'Responded')

    )
	name = models.CharField(max_length=500,default='')
	email=models.CharField(max_length=100,default='')
	query = models.CharField(max_length=50000,blank=True,null=True)
	status = models.CharField(max_length=100, default="Posted" ,choices=STATUS_Response, null=True, blank=True)

	def __str__(self):
		return str(self.name)

class Bootcamp(models.Model):
	STATUS = (
		('Next','Next'),
		('Over','Over'),



	)
	image = models.ImageField(upload_to="Bootcamp-image", default='bootcamp.jpg', null=True,
                              blank=True)
	course_id = models.ForeignKey(course_tb, on_delete=models.CASCADE, null=True, blank=True)
	task = models.CharField(max_length=500, null=True, blank=True)
	subject= models.CharField(max_length=500, null=True, blank=True)
	bootcamp_code= models.CharField(max_length=500, null=True, blank=True)
	price = models.FloatField(default=0.0)
	date = models.DateTimeField(null=True,blank=True)
	status = models.CharField(max_length=100, default="Next" ,choices=STATUS, null=True, blank=True)


	def __str__(self):
		return str(self.id)


	

AI_Builders/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid
from django.apps import apps
from django.db.models.signals import post_save
from django.db.models.signals import pre_save
from django.dispatch import receiver
# Create your models here.
class CustomUser(AbstractUser):
    # USERTYPES
    # 0: SUPERADMIN
    # 1: ADMIN
    # 2: CUSTOMER

    usertype = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    phone_code = models.CharField(max_length=2, null=True, blank=True)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    pswd = models.CharField(max_length=100, null=True, blank=True)
    user_code = models.CharField(max_length=500, null=True, blank=True)
    profile_image = models.ImageField(upload_to="Profile-image", default='profile_image.png', null=True,
                                     blank=True)
    position = models.CharField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return str(self.username)

    class Meta:
        db_table = "CustomUser"
class Courses(models.Model):
    COURSE_TYPE_CHOICES = (
        ('Paid', 'Paid'),
        ('Free', 'Free'),

    )
    STATUS_CHOICES = (
        ('Now Active', 'Now Active'),
        ('Up Coming', 'Up Coming'),
        ('Completed', 'Completed'),

    )
    STATUS_DETAILS = (
        ('Completed', 'Completed'),
        ('Next video', 'Next video'),
        ('Removed video', 'Removed video'),
    )
    name = models.CharField(max_length=500,null=True,blank=True)
    sub_name = models.CharField(max_length=500, null=True, blank=True)
    course_image = models.ImageField(upload_to="Course-image", default='course1.jpg', null=True,
                                     blank=True)
    category_id = models.ForeignKey('app.Category', on_delete=models.CASCADE, null=True, blank=True)
    task_id = models.ForeignKey('app.Task', on_delete=models.CASCADE, null=True, blank=True)
    author_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    course_code = models.CharField(max_length=500,null=True,blank=True)
    course_type = models.CharField(max_length=100, choices=COURSE_TYPE_CHOICES, null=True, blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, null=True, blank=True)
    price =models.FloatField(default=0.0,null=True, blank=True)
    is_offer =models.BooleanField(default=False,null=True, blank=True)
    credit=models.IntegerField(default=0)
    description=models.CharField(max_length=5000,null=True,blank=True)
    modules = models.ForeignKey('app.Module', on_delete=models.CASCADE, null=True, blank=True)
    miniprojects= models.ForeignKey('app.MiniProject', on_delete=models.CASCADE, null=True, blank=True)
    major_projects= models.ForeignKey('app.MajorProject', on_delete=models.CASCADE, null=True, blank=True)
    total_length_course=models.IntegerField(default=0,null=True, blank=True)
    slots_available=models.IntegerField(default=0,null=True, blank=True)
    slots_remaining = models.IntegerField(default=0,null=True, blank=True)
    joined_slots = models.IntegerField(default=0,null=True, blank=True)
    discount_amount = models.FloatField(default=0.0,null=True, blank=True)
    coupon_discount_amount=models.FloatField(default=0.0,null=True, blank=True)
    tax_amount=models.FloatField(default=0.0,null=True, blank=True)
    total_couponprice_with_tax=models.FloatField(default=0.0,null=True, blank=True)
    batch_id = models.ForeignKey('app.Batches', on_delete=models.CASCADE, null=True, blank=True)
    preview_video = models.FileField(upload_to="Preview_video", null=True, blank=True)
    status = models.CharField(max_length=100, default="Posted", choices=STATUS_DETAILS, null=True, blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True,default=now)
    updated_at = models.DateTimeField(null=True,blank=True)
    deleted_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Courses_createdby")
    updated_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Courses_updatedby")
    deleted_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Courses_deletedby")


    def __str__(self):
            return str(self.name)
    class meta:
        db_table = "Courses"
class Module(models.Model):
    course_id = models.ForeignKey('app.Courses', on_delete=models.CASCADE, null=True, blank=True)

    name = models.CharField(max_length=500,null=True,blank=True)
    module_code = models.CharField(max_length=500,null=True,blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True,default=now)
    updated_at = models.DateTimeField(null=True,blank=True)
    deleted_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Module_createdby")
    updated_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Module_updatedby")
    deleted_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Module_deletedby")


    def __str__(self):
            return str(self.name)
    class meta:
        db_table = "Module"
class MiniProject(models.Model):
    course_id = models.ForeignKey('app.Courses', on_delete=models.CASCADE, null=True, blank=True)

    name = models.CharField(max_length=500,null=True,blank=True)
    mini_project_code = models.CharField(max_length=500,null=True,blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True,default=now)
    updated_at = models.DateTimeField(null=True,blank=True)
    deleted_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MiniProject_createdby")
    updated_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MiniProject_updatedby")
    deleted_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MiniProject_deletedby")


    def __str__(self):
            return str(self.name)
    class meta:
        db_table = "MiniProject"
class MajorProject(models.Model):
    course_id = models.ForeignKey('app.Courses', on_delete=models.CASCADE, null=True, blank=True)

    name = models.CharField(max_length=500,null=True,blank=True)
    major_project_code = models.CharField(max_length=500,null=True,blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True,default=now)
    updated_at = models.DateTimeField(null=True,blank=True)
    deleted_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MajorProject_createdby")
    updated_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MajorProject_updatedby")
    deleted_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="MajorProject_deletedby")


    def __str__(self):
            return str(self.name)
    class meta:
        db_table = "MajorProject"
class Category(models.Model):

    name = models.CharField(max_length=500,null=True,blank=True)
    category_code = models.CharField(max_length=500,null=True,blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True,default=now)
    updated_at = models.DateTimeField(null=True,blank=True)
    deleted_at = models.DateTimeField(null=True,blank=True)
    created_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Category_createdby")
    updated_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Category_updatedby")
    deleted_by = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True,blank=True,related_name="Category_deletedby")


    def __str__(self):
            return str(self.name)
    class meta:
        db_table = "Category"


class Task(models.Model):
    name = models.CharField(max_length=500, null=True, blank=True)
    task_code = models.CharField(max_length=500, null=True, blank=True)
    soft_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(editable=True, default=now)
    updated_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="Task_createdby")
    updated_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="Task_updatedby")
    deleted_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True,
                                   related_name="Task_deletedby")

    def __str__(self):
        return str(self.name)

    class meta:
        db_table = "Task"
class Bootcamp(models.Model):
    STATUS = (
        ('Next', 'Next'),
        ('Over', 'Over')

    )
    name = models.CharField(max_length=500, null=True, blank=True)
    sub_name = models.CharField(max_length=500, null=True, blank=True)

    image = models.ImageField(upload_to="Bootcamp-image", default='bootcamp.jpg', null=True,
                              blank=True)

AI_Builders/aiapp/templates/bootform.html
{% extends 'headerfooter.html' %}
{% block content %}

                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Bootcamp</h1>
                       <!--  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a> -->
                    </div>

                    <!-- Content Row -->
                    <div class="row cat-input">
                        <div class="col-xl-6 col-lg-6">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Bootcamp</h4>
                                </div>
                                <div class="card-body">
                                    <div class="basic-form">
                                        <form action="" method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}

                                            <div class="form-row">
                                                <!--  <div class="form-group col-md-8">
                                                    <label>Image </label>
                                                    

                                                    {{form.image}}
                                                </div>
                                                 -->

                                                 <div class="form-group col-12">
                                                 <label> Image</label>
                                                 <div class="custom-file">
<!--{{form.product_image.url}}-->
                            <input type="file" class="custom-file-input" id="id_image"  name="image">
                            <label class="custom-file-label" for='id_image' >Choose file</label>

                       <!--  {% if form.image %} <img src="{{form.image.url}}" width="25px" height="25px">{% else%}None{% endif%} -->
                                                     </div>
                                                     </div>
                                                 <div class="form-group col-md-6">
                                                    <label>Course </label>
                                                    {{form.course_id}}
                                                </div>
                                                
                                                <div class="form-group col-md-6">
                                                    <label>Task </label>
                                                    {{form.task}}
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label>Subject </label>
                                                    {{form.subject}}
                                                </div>
                                                    

                                                 <div class="form-group col-md-6">
                                                    <label>Price</label>
                                                     {{form.price}}
                                                </div>
                                               

                                               
                                                 <div class="form-group col-md-6">
                                                      <label>Date</label>
                                                      <input type="date" class="form-control" name="date" value="{{form.date.value|date:'Y-M-D'}}" id="id_date">
                                                <!--      {{form.date}}  -->
                                                </div>
                                                
                                                 <div class="form-group col-md-6">
                                                    <label>Status</label>
                                                    {{form.status}}
                                                    
                                                </div> 
                                                

                                                
                                               <!--   <div class="form-group col-md-12">
                                                    <label>Phone Code</label>
                                                    <input type="text" class="form-control" name="phonecode">
                                                </div> -->
                                                 <!-- <div class="form-group col-md-12">
                                                    <label>Phone Number</label>
                                                    <input type="text" class="form-control" name="phoneno">
                                                </div> -->
                                                 <!-- <div class="form-group col-md-12">
                                                    <label>Email</label>
                                                    <input type="text" class="form-control" name="email">
                                                </div> -->
                                                <!--  <div class="form-group col-md-12">
                                                    <label>Password</label>
                                                    <input type="password" class="form-control" name="password">
                                                </div> -->
                                                
                                            </div>
                                           <!--  <div class="form-row">
                                                <div class="form-group col-md-12">
                                                    <label>Description</label>
                                                    <textarea class="form-control" rows="2" cols="12" name="description"></textarea>
                                                </div>
                                            </div> -->
                                          <!--   <div class="form-row ">
                                                <div class="form-group col-md-6">
                                                    <label>Category</label>
                                                    <select id="inputState" class="form-control" name="category">
                                                        <option selected>Choose...</option>
                                                        <option>Option 1</option>
                                                        <option>Option 2</option>
                                                        <option>Option 3</option>
                                                    </select>
                                                </div>
                                                <div class="form-group col-md-5">
                                                    <label>Image Input</label>
                                                    <input type="file" class="form-control-file" name="img">
                                                </div> -->

                                            </div>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>




                    <!-- Table -->

                    <br>
                    <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1> -->
                    <!-- <p class="mb-4">All the products that added</p>
 -->
                    <!-- DataTales Example -->
                  <!--   <div class="card shadow mb-4"> -->
                        <!-- <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Product DataTables</h6>
                        </div> -->
                       <!--  <div class="card-body">
                            <div class="table-responsive"> -->
                                <!-- <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Product Name</th>
                                            <th>Description</th>
                                            <th>Category</th>
                                            <th>Price</th>
                                            <th>Img</th>
                                            <th>Edit & delete</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Position</th>
                                            <th>Office</th>
                                            <th>Age</th>
                                            <th>Start date</th>
                                            <th>Salary</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <tr>
                                            <td>Tiger Nixon</td>
                                            <td>System Architect</td>
                                            <td>Edinburgh</td>
                                            <td>61</td>
                                            <td>2011/04/25</td>
                                            <td>$320,800</td>
                                        </tr>
                                        <tr>
                                            <td>Garrett Winters</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td>63</td>
                                            <td>2011/07/25</td>
                                            <td>$170,750</td>
                                        </tr>
                                        <tr>
                                            <td>Ashton Cox</td>
                                            <td>Junior Technical Author</td>
                                            <td>San Francisco</td>
                                            <td>66</td>
                                            <td>2009/01/12</td>
                                            <td>$86,000</td>
                                        </tr>
                                    </tbody>
                                </table> -->
                            <!-- </div>
                        </div> -->
                   <!--  </div> -->
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
           
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/static/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/static/js/demo/datatables-demo.js"></script>


</body>

</html>

{% endblock %}